---
title: Visualize Difference in Baselines
---

```{r}
library(fs)
library(scico)
library(ggridges)
library(tidyverse)
data_dir <- path("data")
```

```{r}
# p_score_*.csv
score_files <- dir_ls(data_dir, recurse = TRUE, glob = "**/pscore_*.csv")
p_scores <- map_dfr(score_files, \(fp) {
  read_csv(fp, show_col_types = FALSE) |>
    mutate(
      noise_level = as.numeric(str_match(path_file(fp), "pscore_([0-9]+(?:\\.[0-9]+)?)\\.csv$")[, 2]),
      id = row_number(),
      .before = 1
    )
})

# swiss_noise_*_embedding.csv
embed_files <- dir_ls(data_dir, recurse = TRUE, glob = "**/swiss_noise_*_embedding.csv")
embeddings <- map_dfr(embed_files, \(fp) {
  read_csv(fp, show_col_types = FALSE) |>
    mutate(
      noise_level = as.numeric(str_match(path_file(fp), "swiss_noise_([^_]+)_embedding\\.csv$")[, 2]),
      id = row_number(),
      .before = 1,
    )
})
```

```{r}
theme_set(theme_bw())
embeddings |>
    left_join(p_scores) |>
    ggplot() +
    geom_point(
        aes(
            `0`, `1`,
            col = log1p(score),
            size = log1p(score),
            )
        ) +
    scale_size(range = c(0, .8)) +
    scale_color_scico(palette = "berlin") +
    facet_wrap(~ noise_level, nrow = 2) +
    labs(col = "log(1 + LOO score)", size = "log(1 + LOO score)", x = "t-SNE 1", y = "t-SNE2") +
    theme(
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank()
    )
ggsave("~/Downloads/p_scores.png", width = 7, height = 4)

ggplot(p_scores) +
    stat_ecdf(aes(log10(score), group = factor(noise_level), col = noise_level)) +
    scale_color_scico(palette = "glasgow", direction = -1) +
    scale_x_continuous(limits = c(-1.5, 1.6)) +
    labs(
        y = "P(Perturbation Score < t)",
        x = "Perturbation Score",
        col = "Noise Level"
    )
ggsave("~/Downloads/p_score_ecdf.png", width = 6.5, height = 4)

embeddings |>
    left_join(p_scores) |>
    ggplot() +
    geom_point(
        aes(
            `0`, `1`,
            col = `2`
            ),
            size = 0.4
        ) +
    scale_color_gradient(low='#B776A6', high='#BAC4A2') +
    labs(col = "manifold\nparameter", x = "t-SNE 1", y = "t-SNE2") +
    facet_wrap(~ noise_level, nrow = 2) +
    theme(
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank()
    )
ggsave("~/Downloads/noisy_embedding.png", width = 7, height = 4)
```

```{r}
embeddings |>
    left_join(p_scores) |>
    filter(noise_level == 0.5) |>
    ggplot() +
    geom_point(
        aes(
            `0`, `1`,
            col = log1p(score),
            size = log1p(score)
            )
        ) +
    scale_size(range = c(0, 1.5)) +
    scale_color_scico(palette = "berlin") +
    labs(col = "log(1 + LOO score)", size = "log(1 + LOO score)", x = "t-SNE 1", y = "t-SNE2") +
    theme(
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank()
    )
ggsave("~/Downloads/p_scores_0.5.png", width = 4.5, height = 3)

embeddings |>
    left_join(p_scores) |>
    filter(noise_level == 0.5) |>
    ggplot() +
    geom_point(
        aes(
            `0`, `1`,
            col = `2`
            ),
            size = 0.7
        ) +
    scale_color_gradient(low='#B776A6', high='#BAC4A2') +
    labs(col = "manifold\nparameter", x = "t-SNE 1", y = "t-SNE2") +
    theme(
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank()
    )
ggsave("~/Downloads/noisy_embedding_0.5.png", width = 4.5, height = 3)
```

```{r}
time_files <- dir_ls(data_dir, recurse = TRUE, glob = "**/runtime*txt")
runtimes <- map_dfr(time_files, \(fp)
  read_table(fp, show_col_types = FALSE, col_names = FALSE) |>
    mutate(
      noise_level = as.numeric(str_match(path_file(fp), "([0-9]+(?:\\.[0-9]+)?)")[, 2]),
      id = row_number(),
      method = case_when(
        str_detect(fp, "dist") ~ "distortions",
        str_detect(fp, "sleepwalk") ~ "sleepwalk",
        TRUE ~ "neMDBD"
      ),
      .before = 1
    ) |>
    rename(runtime = X1)
)

library(xtable)
runtimes |>
    group_by(method) |>
    summarise(
        mean = mean(runtime), sd = sd(runtime)
    ) |>
    xtable()
```