---
title: Visualize Difference in Baselines
---

```{r}
library(fs)
library(scico)
library(ggridges)
library(tidyverse)
data_dir <- path("data")
```

```{r}
# p_score_*.csv
score_files <- dir_ls(data_dir, recurse = TRUE, glob = "**/pscore_*.csv")
p_scores <- map_dfr(score_files, \(fp) {
  read_csv(fp, show_col_types = FALSE) |>
    mutate(
      noise_level = as.numeric(str_match(path_file(fp), "pscore_([0-9]+(?:\\.[0-9]+)?)\\.csv$")[, 2]),
      id = row_number(),
      .before = 1
    )
})

# swiss_noise_*_embedding.csv
embed_files <- dir_ls(data_dir, recurse = TRUE, glob = "**/swiss_noise_*_embedding.csv")
embeddings <- map_dfr(embed_files, \(fp) {
  read_csv(fp, show_col_types = FALSE) |>
    mutate(
      noise_level = as.numeric(str_match(path_file(fp), "swiss_noise_([^_]+)_embedding\\.csv$")[, 2]),
      id = row_number(),
      .before = 1,
    )
})
```

```{r}
theme_set(theme_bw())
embeddings |>
    left_join(p_scores) |>
    ggplot() +
    geom_point(
        aes(
            `0`, `1`, #col = `1`,
            col = score,
            size = score
            )
        ) +
    scale_size(range = c(0.001, .8)) +
    scale_color_scico(palette = "berlin") +
    facet_wrap(~ noise_level, nrow = 2)

ggplot(p_scores) +
    stat_ecdf(aes(log10(score), group = factor(noise_level), col = noise_level)) +
    scale_color_scico(palette = "glasgow", direction = -1) +
    scale_x_continuous(limits = c(-1.5, 1.6)) +
    labs(
        y = "P(Perturbation Score < t)",
        x = "Perturbation Score",
        col = "Noise Level"
    )
```